CREATE DATABASE QLPHONGKHAMNHAKHOA2
GO

USE QLPHONGKHAMNHAKHOA2
GO

CREATE TABLE TAIKHOAN(
	SDT VARCHAR(50) PRIMARY KEY,
	MATKHAU VARCHAR(50),
	LOAITAIKHOAN VARCHAR(5) NOT NULL

	CONSTRAINT CHK_LOAITAIKHOAN CHECK(LOAITAIKHOAN IN ('QTV', 'BN', 'NV', 'NS'))
)
GO



-----CAC LOAI NGUOI DUNG----------------
CREATE TABLE QUANTRIVIEN(
	MaQTV VARCHAR(20) PRIMARY KEY,
	QTVSdt VARCHAR(50),
	QTVHoten NVARCHAR(50),

	LOAITAIKHOAN AS 'QTV' PERSISTED
	CONSTRAINT FK_QTV_TK FOREIGN KEY(QTVSdt) REFERENCES TAIKHOAN(SDT)
)
GO


CREATE TABLE NHANVIEN(
	MaNV VARCHAR(20) PRIMARY KEY,
	NVSdt VARCHAR(50),
	NVHoten NVARCHAR(50),

	LOAITAIKHOAN AS 'NV' PERSISTED
	CONSTRAINT FK_NV_TK FOREIGN KEY(NVSdt) REFERENCES TAIKHOAN(SDT)
)
GO

CREATE TABLE BENHNHAN(
	MaBN VARCHAR(20) PRIMARY KEY,
	BNSdt VARCHAR(50),
	BNHoten NVARCHAR(50),
	BNNgaysinh DATE,
	BNDiachi NVARCHAR(100),

	LOAITAIKHOAN AS 'BN' PERSISTED
	CONSTRAINT FK_BN_TK FOREIGN KEY(BNSdt) REFERENCES TAIKHOAN(SDT)
)
GO

CREATE TABLE NHASI(
	MaNS VARCHAR(20) PRIMARY KEY,
	NSSdt VARCHAR(50),
	NSHoten NVARCHAR(50),

	LOAITAIKHOAN AS 'NS' PERSISTED
	CONSTRAINT FK_NS_TK FOREIGN KEY(NSSdt) REFERENCES TAIKHOAN(SDT)
)
GO
--------------------------------------------------------------------


CREATE TABLE LICHLAMVIEC(
	MaLich VARCHAR(20) PRIMARY KEY,
	MaNSLich VARCHAR(20),
	LichTrong DATETIME

	CONSTRAINT FK_LICH_NS FOREIGN KEY(MaNSLich) REFERENCES NHASI(MaNS)
)

--------DICH VU VA THUOC------------------
CREATE TABLE DICHVU(
	MaDV VARCHAR(20) PRIMARY KEY,
	TenDV NVARCHAR(100),
	PhiDichVu INT
)
GO

CREATE TABLE THUOC(
	MaThuoc VARCHAR(20) PRIMARY KEY,
	TenThuoc NVARCHAR(100),
	DonViTinh NVARCHAR(20),
	ChiDinh NVARCHAR(100),
	SLTonKho INT,
	NgayHetHan DATE,
)
GO
---------------------------------------------------------

-------CAC BANG LIEN QUAN DEN HO SO BENH NHAN------------
CREATE TABLE HOSO(
	MaHS VARCHAR(20) PRIMARY KEY,
	HSNgayKham DATE,
	NSKham VARCHAR(20),
	BNKham VARCHAR(20),

	CONSTRAINT FK_HOSO_NS FOREIGN KEY(NSKham) REFERENCES NHASI(MaNS),
	CONSTRAINT FK_HOSO_BN FOREIGN KEY(BNKham) REFERENCES BENHNHAN(MaBN)
)
GO

CREATE TABLE HOSO_THUOC(
	MaHSKham VARCHAR(20) NOT NULL,
	MaThuocChiDinh VARCHAR(20) NOT NULL,
	SoLuong INT

	CONSTRAINT FK_HST_HOSO FOREIGN KEY(MaHSKham) REFERENCES HOSO(MaHS),
	CONSTRAINT FK_HST_THUOC	FOREIGN KEY(MaThuocChiDinh) REFERENCES THUOC(MaThuoc),

	PRIMARY KEY(MaHSKham, MaThuocChiDinh)
)

GO

CREATE TABLE HOSO_DICHVU(
	MaHSKham VARCHAR(20) NOT NULL,
	MaDVSuDung VARCHAR(20) NOT NULL,
	
	CONSTRAINT FK_HSDV_HOSO FOREIGN KEY(MaHSKham) REFERENCES HOSO(MaHS),
	CONSTRAINT FK_HSDV_DICHVU FOREIGN KEY(MaDVSuDung) REFERENCES DICHVU(MaDV),
	
	PRIMARY KEY(MaHSKham, MaDVSuDung)
)
GO
---------------------


------HOA DON-----------------------
CREATE TABLE HOADON(
	MaHoaDon VARCHAR(20) PRIMARY KEY,
	TongTien INT,
	MaBNThanhToan VARCHAR(20)

	CONSTRAINT FK_HD_BN FOREIGN KEY(MaBNThanhToan) REFERENCES BENHNHAN(MaBN)
)
GO
------------------------------------

-------LICH HEN---------------------
CREATE TABLE LICHHEN(
	MaLichHen VARCHAR(20) PRIMARY KEY,
	ThoiGian DATETIME,
	MaBNHen VARCHAR(20),
	MaNSHen VARCHAR(20)

	CONSTRAINT FK_LH_BN FOREIGN KEY(MaBNHen) REFERENCES BENHNHAN(MaBN),
	CONSTRAINT FK_LH_NS FOREIGN KEY(MaNSHen) REFERENCES NHASI(MaNS)
)
GO
------------------------------------

